version: '3.7'

services:
  web:
    build: ./taha_back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./taha_back/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shaya_user
      - POSTGRES_PASSWORD=Mdb@@1374
      - POSTGRES_DB=shaya_db

volumes:
  postgres_data:
