# Generated by Django 3.1.6 on 2021-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0014_auto_20210217_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default='22791', max_length=7),
        ),
    ]
