# Generated by Django 3.1.6 on 2021-02-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0016_auto_20210219_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='related_affiliate',
            new_name='related_profile',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='related_affiliate',
            new_name='related_profile',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='related_affiliate',
        ),
        migrations.AddField(
            model_name='wallet',
            name='related_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tahaApp.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default='34559', max_length=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='types',
            field=models.CharField(choices=[('a', 'Add'), ('m', 'Minus')], default='m', max_length=2),
        ),
    ]
