# Generated by Django 3.1.6 on 2021-02-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0017_auto_20210220_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default='88440', max_length=7),
        ),
    ]
