# Generated by Django 3.1.6 on 2021-02-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0018_auto_20210220_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default='29050', max_length=7),
        ),
    ]
