# Generated by Django 3.1.6 on 2021-02-22 03:06

from django.db import migrations, models
import tahaApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0019_auto_20210222_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default=tahaApp.models.random_with_N_digits, max_length=7),
        ),
    ]
